<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DevAtlas.Common\DevAtlas.Common.csproj" />
    <ProjectReference Include="..\DevAtlas.Core.Domain.Entities\DevAtlas.Core.Domain.Entities.csproj" />
    <ProjectReference Include="..\DevAtlas.Core.Domain.Abstractions\DevAtlas.Core.Domain.Abstractions.csproj" />
    <ProjectReference Include="..\DevAtlas.Core.Domain.Events\DevAtlas.Core.Domain.Events.csproj" />
    <ProjectReference Include="..\DevAtlas.Core.Domain.Services\DevAtlas.Core.Domain.Services.csproj" />
    <ProjectReference Include="..\DevAtlas.Core.Application.Models\DevAtlas.Core.Application.Models.csproj" />
    <ProjectReference Include="..\DevAtlas.Core.Application.Abstractions\DevAtlas.Core.Application.Abstractions.csproj" />
    <ProjectReference Include="..\DevAtlas.Core.Application.Services\DevAtlas.Core.Application.Services.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
